MAP_ROW_COUNT = 9
MAP_COL_COUNT = 9
MAP_CELL_SIZE = 8

MIN_GRASS_PER_ROW = 1
MAX_GRASS_PER_ROW = 2
MIN_SAND_PER_ROW = 2
MAX_SAND_PER_ROW = 4

GRASS_TYPE = 'g'
SAND_TYPE = 's'
WATER_TYPE = 'w'
TILE_IDENTIFIERS = {GRASS_TYPE, SAND_TYPE, WATER_TYPE}
NEUTRAL = 'n'

MAP_FIRST_TILE_OFFSET = 22

DESPAWN = 'd' BLOCK = 'b'
MAP_EXIT_POLICIES = {DESPAWN, BLOCK}