MAP_ROW_COUNT = 9
MAP_COL_COUNT = 9
MAP_CELL_SIZE = 8

MIN_GRASS_PER_ROW = 1
MAX_GRASS_PER_ROW = 2
MIN_SAND_PER_ROW = 2
MAX_SAND_PER_ROW = 4

GRASS_TILE_IDNTIFIER = 'g'
SAND_TILE_IDNTIFIER = 's'
WATER_TILE_IDNTIFIER = 'w'

MAP_FIRST_TILE_OFFSET = 22