ENEMY_STEP_SOUND_1 = 0
ENEMY_DEATH_SOUND_1 = 1
ENEMY_DEATH_SOUND_2 = 2
BULLET_SHOT_SOUND_1 = 3
BULLET_DESPAWN_SOUND = 4
PLAYER_DEATH_SOUND = 5
ENEMY_STEP_SOUND_2 = 6
BULLET_SHOT_SOUND_2 = 7

LEVEL_MUSIC =  0
VICTORY_MUSIC = 4
NO_MUSIC = 5