GRASS_TILE_SPRITE = 1
SAND_TILE_SPRITE = 2
WATER_TILE_SPRITE = 3

PLAYER_GRASS_SPRITE = 4
PLAYER_SAND_SPRITE = 5
PLAYER_WATER_LEFT_SPRITE = 6
PLAYER_WATER_RIGHT_SPRITE = 7
PLAYER_GRASS_BACK_SPRITE = 8
PLAYER_SAND_BACK_SPRITE = 9
PLAYER_WATER_BACK_SPRITE = 10
PLAYER_WATER_FORWARD_SPRITE = 11

GRASS_BULLET_SPRITE = 13
SAND_BULLET_SPRITE = 14
WATER_BULLET_SPRITE = 15

FIRST_DESPAWN_SPRITE_FRAME = 17
LAST_DESPAWN_SPRITE_FRAME = 19

ENEMY_NEUTRAL_SPRITE = 28
ENEMY_GRASS_SPRITE = 29
ENEMY_SAND_SPRITE = 30
ENEMY_WATER_SPRITE = 31